<div id="delivery-modal" class="modal fade" tabindex="-1" role="dialog" style="z-index:9999 !important; margin-top:10px;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Delivery terms and conditions</h4>
			</div>
			<div class="modal-body">
                <h1>Terms & Conditions</h1>
				<p>
                It is the responsibility of the Customer to carefully review these Terms & Conditions. Terms and
Conditions may change without notice. Once garments are entrusted to us either through in-store drop
off or delivery/pickup service the Customer agrees to and accepts the following Terms & Conditions:
                </p>
                <h3>Payments &amp; Estimates</h3>
				<p>It is our policy to collect payment for services provided prior to the garments leaving our premises and
                we reserve the right to retain all garments until full payment is received. In the event that an estimate is
                provided, we reserve the right to adjust the final charge as processing may require additional resources
                to complete. Prices listed on our website are for the most common types of garments processed and are
                base prices which are subject to change as garments are processed. Price estimates can only be
                provided by a member of management and we will not honor or accept prices generated by others (ie
                blogs, other websites, review sites etc). We reserve the right to refuse any garments prior to processing
                for any reason.</p>
                <h3>Garment Weakness &amp; Processing</h3>
                <p>Garments can possess inherent weaknesses or manufacturing defects in materials that can negatively
                affect the ultimate outcome of processing through dry cleaning, laundering, pressing, spot cleaning or
                other. Nevertheless, although we will exercise the utmost care for garments entrusted to us for cleaning
                and other provided services, we cannot assume responsibility for such weaknesses or manufacturing
                defects that are not readily apparent to us prior to processing. This applies, but is not limited to, suedes,
                leathers, silks, satins, double-faced fabrics, vinyls, polyurethanes etc. Responsibility is also disclaimed for
                but is not limited to trims, beads, buckles, buttons, bells, sequins and any other attachments.</p>
                <p>All garment care tag instructions will be adhered to if provided with or attached to garments. In the
                event that a garment is missing a care tag it is ultimately the Customers responsibility to provide us with
                a garment care tag prior to processing. In the event that a garment care tag is not available, we will
                exercise our best judgement as to the appropriate cleaning methods for each garment but will not
                assume any responsibility for any resulting damage for lack thereof.</p>
                <p>Garments that require dry cleaning, spot cleaning and or laundering do carry risk of color loss, shrinkage
                and other damage to weak or tender fabrics that cannot be mitigated during such processes and
                therefore we will not assume any risk or accept responsibility for damaged garments where the
                prescribed cleaning method on the care tag is followed. This includes but is not limited to damage
                incurred as a result of adherence to any provided care tags or where we have agreed to a certain
                method prior to cleaning.</p>
                <h3>Missing or Damaged Items</h3>
                <p>If picking up in-store it is the responsibility of the Customer to inspect all garments or to report any
                damage to or any missing garments prior to leaving our premises. In the event that the garments are
                delivered, it is the responsibility of the Customer to report any such damaged or missing items within 48
                hours of being delivered. All garments must be returned for our inspection in the same condition as it
                was when delivered. Any garments that appear worn or used after returned to Customer will not be
                considered for any damage claims. We reserve the right to inspect all items returned and to investigate
                why such damage may have occurred, including but not limited to possible manufacturers defects. The
                Customer will allow an adequate amount of time to conduct such investigations. In any event our
                liability with respect to any damages or missing garment will not exceed ten (10) times the amount
                charged for processing the garment.</p>
                <h3>Delivery and Items In-Transit</h3>
                <p>When delivery/pickup is requested it is the responsibility of the Customer to provide us with a safe and
                weather-proof location for storage. When not provided, we will exercise our best judgement in
                choosing a location. Nevertheless, due to the risk of leaving items unattended or the risks of damage
                while garments are in transit, we will not assume any responsibility for damage to or for missing
                garments once they have left our premises. We will make all reasonable attempts to deliver and pick up
                your garments within our agreed to schedule, but reserve the right to delay or reschedule based upon
                but not limited to factors such as weather, traffic, inaccessibility and governmental mandates etc. In
                circumstances where entry to delivery/pickup locations are unavailable (such as a building concierge
                etc.) we will make all attempts to reach the Customer to gain entry but shall not be held responsible for
                garments due to inaccessibility of delivery locations and a re-delivery charge may apply. We reserve the
                right to charge a $15.00 fee in circumstances where a pickup is requested but items are not left for
                pickup by the Customer once our driver arrives and we have made an adequate attempt to contact the
                Customer (email, phone, text etc.).</p>
            </div>
            <div class="modal-footer clearfix">
				<button type="button" class="btn" data-dismiss="modal">Close</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->